### ISSUE TITLE
exclude conda installed packages

### ISSUE THREAD

**Issue by j9ac9k** [massongit/pyenv-pip-update#2]
This plugin should probably skip over packages that were not installed by `pip` but by the `conda` package manager.  If we want to update conda installed packages, we should just activate that environment and run `conda update --all`.  

I'm not sure how to get a `pip list` that includes only packages installed via `pip` and not `conda` though.

**Comment by massongit** [comment]
I fixed it ( 57029120e3cf6dcd8a08b60537b8c5d5269827bd ).
